2022-07-06 11:15:09,208 - INFO - Will watch for changes in these directories: ['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading']
2022-07-06 11:15:09,210 - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-07-06 11:15:09,220 - INFO - Started reloader process [6104] using watchgod
2022-07-06 11:15:10,842 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:15:11,082 - INFO - Started server process [12608]
2022-07-06 11:15:11,082 - INFO - Waiting for application startup.
2022-07-06 11:15:11,082 - INFO - Application startup complete.
2022-07-06 11:26:17,513 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 11:26:19,281 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:26:19,318 - INFO - Started server process [4376]
2022-07-06 11:26:19,318 - INFO - Waiting for application startup.
2022-07-06 11:26:19,318 - INFO - Application startup complete.
2022-07-06 11:26:26,520 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 11:26:28,182 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:26:28,218 - INFO - Started server process [10976]
2022-07-06 11:26:28,219 - INFO - Waiting for application startup.
2022-07-06 11:26:28,219 - INFO - Application startup complete.
2022-07-06 11:27:30,894 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 11:27:32,634 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:27:32,669 - INFO - Started server process [2056]
2022-07-06 11:27:32,669 - INFO - Waiting for application startup.
2022-07-06 11:27:32,669 - INFO - Application startup complete.
2022-07-06 11:30:18,265 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\routers\\dashboard\\technical_analysis.py']'. Reloading...
2022-07-06 11:30:19,967 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:30:20,002 - INFO - Started server process [12060]
2022-07-06 11:30:20,003 - INFO - Waiting for application startup.
2022-07-06 11:30:20,003 - INFO - Application startup complete.
2022-07-06 11:32:51,822 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 21, in get_pnl_for_report_analysis
    return pnlCal.get_pnl(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\technical_analysis_service.py", line 120, in get_pnl
    allTradeData = res['data']['recordData']
KeyError: 'data'
2022-07-06 11:56:45,137 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 11:56:47,617 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:56:47,656 - INFO - Started server process [11652]
2022-07-06 11:56:47,656 - INFO - Waiting for application startup.
2022-07-06 11:56:47,656 - INFO - Application startup complete.
2022-07-06 11:58:04,542 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 11:58:06,262 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 11:58:06,300 - INFO - Started server process [11292]
2022-07-06 11:58:06,300 - INFO - Waiting for application startup.
2022-07-06 11:58:06,300 - INFO - Application startup complete.
2022-07-06 13:31:18,129 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\report_service.py']'. Reloading...
2022-07-06 13:31:29,422 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:31:29,702 - INFO - Started server process [12940]
2022-07-06 13:31:29,702 - INFO - Waiting for application startup.
2022-07-06 13:31:29,702 - INFO - Application startup complete.
2022-07-06 13:34:05,672 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:34:07,495 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:34:07,531 - INFO - Started server process [12896]
2022-07-06 13:34:07,532 - INFO - Waiting for application startup.
2022-07-06 13:34:07,532 - INFO - Application startup complete.
2022-07-06 13:34:53,246 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\technical_analysis_service.py']'. Reloading...
2022-07-06 13:34:54,989 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:34:55,028 - INFO - Started server process [12436]
2022-07-06 13:34:55,028 - INFO - Waiting for application startup.
2022-07-06 13:34:55,028 - INFO - Application startup complete.
2022-07-06 13:36:57,537 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\core\\endpoints.py']'. Reloading...
2022-07-06 13:36:59,333 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:36:59,382 - INFO - Started server process [13052]
2022-07-06 13:36:59,382 - INFO - Waiting for application startup.
2022-07-06 13:36:59,382 - INFO - Application startup complete.
2022-07-06 13:37:50,198 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:37:51,940 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:37:51,975 - INFO - Started server process [12432]
2022-07-06 13:37:51,975 - INFO - Waiting for application startup.
2022-07-06 13:37:51,976 - INFO - Application startup complete.
2022-07-06 13:38:36,943 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:38:38,628 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:38:38,668 - INFO - Started server process [3212]
2022-07-06 13:38:38,669 - INFO - Waiting for application startup.
2022-07-06 13:38:38,669 - INFO - Application startup complete.
2022-07-06 13:38:46,149 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:38:47,882 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:38:47,919 - INFO - Started server process [3816]
2022-07-06 13:38:47,919 - INFO - Waiting for application startup.
2022-07-06 13:38:47,919 - INFO - Application startup complete.
2022-07-06 13:39:37,259 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:39:39,001 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:39:39,039 - INFO - Started server process [9096]
2022-07-06 13:39:39,039 - INFO - Waiting for application startup.
2022-07-06 13:39:39,040 - INFO - Application startup complete.
2022-07-06 13:40:02,845 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:40:04,590 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:40:04,627 - INFO - Started server process [12684]
2022-07-06 13:40:04,628 - INFO - Waiting for application startup.
2022-07-06 13:40:04,628 - INFO - Application startup complete.
2022-07-06 13:43:50,092 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:43:51,811 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:43:51,847 - INFO - Started server process [4748]
2022-07-06 13:43:51,847 - INFO - Waiting for application startup.
2022-07-06 13:43:51,847 - INFO - Application startup complete.
2022-07-06 13:44:24,181 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:44:25,903 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:44:25,940 - INFO - Started server process [12048]
2022-07-06 13:44:25,940 - INFO - Waiting for application startup.
2022-07-06 13:44:25,940 - INFO - Application startup complete.
2022-07-06 13:45:15,524 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:45:17,236 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:45:17,270 - INFO - Started server process [2468]
2022-07-06 13:45:17,271 - INFO - Waiting for application startup.
2022-07-06 13:45:17,271 - INFO - Application startup complete.
2022-07-06 13:46:26,576 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:46:28,599 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:46:28,638 - INFO - Started server process [11480]
2022-07-06 13:46:28,638 - INFO - Waiting for application startup.
2022-07-06 13:46:28,638 - INFO - Application startup complete.
2022-07-06 13:47:06,743 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:47:08,718 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:47:08,758 - INFO - Started server process [12316]
2022-07-06 13:47:08,758 - INFO - Waiting for application startup.
2022-07-06 13:47:08,759 - INFO - Application startup complete.
2022-07-06 13:48:35,559 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:48:37,260 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:48:37,296 - INFO - Started server process [2648]
2022-07-06 13:48:37,296 - INFO - Waiting for application startup.
2022-07-06 13:48:37,296 - INFO - Application startup complete.
2022-07-06 13:55:26,552 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:55:28,303 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:55:28,338 - INFO - Started server process [2056]
2022-07-06 13:55:28,338 - INFO - Waiting for application startup.
2022-07-06 13:55:28,338 - INFO - Application startup complete.
2022-07-06 13:57:12,288 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 13:57:14,112 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 13:57:14,148 - INFO - Started server process [11816]
2022-07-06 13:57:14,149 - INFO - Waiting for application startup.
2022-07-06 13:57:14,149 - INFO - Application startup complete.
2022-07-06 13:59:39,808 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\routers\\dashboard\\technical_analysis.py']'. Reloading...
2022-07-06 14:00:19,383 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\routers\\dashboard\\technical_analysis.py']'. Reloading...
2022-07-06 14:00:47,260 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\routers\\dashboard\\technical_analysis.py']'. Reloading...
2022-07-06 14:01:36,613 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\contract_size_service.py']'. Reloading...
2022-07-06 14:01:38,504 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:01:38,541 - INFO - Started server process [12052]
2022-07-06 14:01:38,541 - INFO - Waiting for application startup.
2022-07-06 14:01:38,541 - INFO - Application startup complete.
2022-07-06 14:02:49,720 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\util\url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 23, in post_url
    res = post(url=requestUrl, json=requestDict)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 20, in get_contract_size
    res = self.__get_product_list(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 17, in __get_product_list
    return CommonHelper.post_url(cls.__url, request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 31, in post_url
    traceback.print_exc(file=LOG_FILENAME) # May fall apart if file does not exist (AttributeError: 'str' object has no attribute 'write')
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
AttributeError: 'str' object has no attribute 'write'
2022-07-06 14:03:30,673 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 14:03:32,465 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:03:32,508 - INFO - Started server process [11904]
2022-07-06 14:03:32,508 - INFO - Waiting for application startup.
2022-07-06 14:03:32,508 - INFO - Application startup complete.
2022-07-06 14:03:46,569 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 224, in openapi
    return JSONResponse(self.openapi())
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 199, in openapi
    self.openapi_schema = get_openapi(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\openapi\utils.py", line 418, in get_openapi
    definitions = get_model_definitions(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\utils.py", line 28, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic\schema.py", line 590, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 631, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 258, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 536, in pydantic.schema.field_type_schema
  File "pydantic\schema.py", line 932, in pydantic.schema.field_singleton_schema
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
2022-07-06 14:04:18,951 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 14:04:20,674 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:04:20,710 - INFO - Started server process [12768]
2022-07-06 14:04:20,710 - INFO - Waiting for application startup.
2022-07-06 14:04:20,710 - INFO - Application startup complete.
2022-07-06 14:04:39,504 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\util\url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 23, in post_url
    res = post(url=requestUrl, json=requestDict)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 20, in get_contract_size
    res = self.__get_product_list(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 17, in __get_product_list
    return CommonHelper.post_url(cls.__url, request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 31, in post_url
    traceback.print_exc(file=LOG_FILENAME) # May fall apart if file does not exist (AttributeError: 'str' object has no attribute 'write')
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
AttributeError: 'str' object has no attribute 'write'
2022-07-06 14:09:16,609 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\util\url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 23, in post_url
    res = post(url=requestUrl, json=requestDict)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 20, in get_contract_size
    res = self.__get_product_list(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 17, in __get_product_list
    return CommonHelper.post_url(cls.__url, request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 31, in post_url
    traceback.print_exc(file=LOG_FILENAME) # May fall apart if file does not exist (AttributeError: 'str' object has no attribute 'write')
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
AttributeError: 'str' object has no attribute 'write'
2022-07-06 14:10:44,626 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 14:10:46,622 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:10:46,660 - INFO - Started server process [8724]
2022-07-06 14:10:46,660 - INFO - Waiting for application startup.
2022-07-06 14:10:46,660 - INFO - Application startup complete.
2022-07-06 14:10:49,651 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\schemas\\technical_analysis_schemas.py']'. Reloading...
2022-07-06 14:10:51,452 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:10:51,490 - INFO - Started server process [3844]
2022-07-06 14:10:51,490 - INFO - Waiting for application startup.
2022-07-06 14:10:51,490 - INFO - Application startup complete.
2022-07-06 14:11:34,672 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\util\url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 23, in post_url
    res = post(url=requestUrl, json=requestDict)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\Lib\site-packages\requests\models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://192.168.123.221:9030jLogin/product/downloadProductList

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 20, in get_contract_size
    res = self.__get_product_list(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 17, in __get_product_list
    return CommonHelper.post_url(cls.__url, request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\common\common_helper.py", line 31, in post_url
    traceback.print_exc(file=LOG_FILENAME) # May fall apart if file does not exist (AttributeError: 'str' object has no attribute 'write')
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\spintern\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 121, in print_exception
    print(line, file=file, end="")
AttributeError: 'str' object has no attribute 'write'
2022-07-06 14:16:01,559 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\common\\common_helper.py']'. Reloading...
2022-07-06 14:16:03,437 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:16:03,477 - INFO - Started server process [7632]
2022-07-06 14:16:03,478 - INFO - Waiting for application startup.
2022-07-06 14:16:03,478 - INFO - Application startup complete.
2022-07-06 14:16:03,976 - ERROR - None
2022-07-06 14:16:54,024 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\core\\endpoints.py']'. Reloading...
2022-07-06 14:16:55,827 - WARNING - The --reload flag should not be used in production on Windows.
2022-07-06 14:16:55,869 - INFO - Started server process [10112]
2022-07-06 14:16:55,869 - INFO - Waiting for application startup.
2022-07-06 14:16:55,870 - INFO - Application startup complete.
2022-07-06 14:17:25,764 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 21, in get_contract_size
    contract_size = res['data']['recordData']
KeyError: 'data'
2022-07-06 14:35:36,324 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 21, in get_contract_size
    contract_size = res['data']['recordData']
KeyError: 'data'
2022-07-06 14:35:46,652 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\routers\dashboard\technical_analysis.py", line 35, in get_contract_size
    return contractSize.get_contract_size(request)
  File "C:\Users\spintern\Documents\GitHub\fastapi-algo-trading\app\services\contract_size_service.py", line 21, in get_contract_size
    contract_size = res['data']['recordData']
KeyError: 'data'
2022-07-06 16:26:11,471 - WARNING - WatchGodReload detected file change in '['C:\\Users\\spintern\\Documents\\GitHub\\fastapi-algo-trading\\app\\services\\report_service.py']'. Reloading...
